### ISSUE TITLE
Calibration Constant?

### ISSUE THREAD

**Issue by polygonfuture** [veebch/photon#14]
Hi there,

I see your calibration constant is set to 15.   Why chose 15 over typical regular constants such as 12.5 and 14?  Could you tell me about this value choice?  (Newbie here and trying to understand this more)

**Comment by veebch** [comment]
The original is in the code (I think). I was thinking about making this something that can be set via the UI for people who use different sensors/cases. The sunny 16 rule for direct sunlight would be a good method for those who don't have a second meter to check against.

Anyway, I digress. Short answer: it's in the code.
