### ISSUE TITLE
BH1750 instead of BH1745

### ISSUE THREAD

**Issue by Mojojojooo** [veebch/photon#16]
Hi, I'm planning to build this and currently BH1745( Colour and luminance sensor) has been unavailable for a long time. Since the calculation part just shows that luminance is used. Can BH1750 which is just a luminance sensor be used instead of BH1745 ?

**Comment by Mojojojooo** [comment]
How are the RGB values being used for calculation? As 1750 won't have RBG values any idea how can we bypass it ?

**Comment by veebch** [comment]
They are only used in determining the colour of the EV reading. It should be easy to bypass.

**Comment by veebch** [comment]
I would just set it to white (255,255,255)

**Comment by polygonfuture** [comment]
@Mojojojooo BH1745 is not unavailable.  

Pimoroni keeps it in stock regularly:  https://shop.pimoroni.com/products/bh1745-luminance-and-colour-sensor-breakout?variant=12767599755347

**Comment by Mojojojooo** [comment]
@polygonfuture I mean to say it's hard to get it in India. So I was looking for an alternative.

**Comment by veebch** [comment]
No one chipped in, but I made an alternative. I'll share it as soon as it's ready

[preview](https://www.veeb.ch/projects/flash-aaahhh-ahhhhhh)
