### ISSUE TITLE
Stupid noob question

### ISSUE THREAD

**Issue by GitGitKangaroo** [veebch/photon#18]
Hi. I have zero Python experience and was interested in trying this as a first build. If I attempt to do this with qwiic connectors rather than soldering, will I need to make changes to the code?. Sorry, I'm sure that's a really dumb question but I've no idea how this works.

**Comment by veebch** [comment]
Not dumb at all. 

I've not used qwiic connectors, so I will let someone else provide an answer. My first impression is that you might end up using different pins to talk to the hardware, so the code would need to be tweaked by changing the pin numbers. 

Anyway, I'm making stuff up, so I'll be quiet. Good luck with the build!
