### ISSUE TITLE
sudo: ampy: command not found

### ISSUE THREAD

**Issue by jonyv0992** [veebch/photon#2]
Every time I run the scrip as copied I get the same error 4 times. Everything else up to that point works well

**Comment by veebch** [comment]
It sounds like ampy isn't installed for root?

**Comment by jonyv0992** [comment]
Now I get an error when running the command again to install the files saying they do not exist

**Comment by veebch** [comment]
I've updated the readme to remove the use of sudo with ampy. 

As for the files not existing: Check that they are there. Closing this for now because it's an `ampy` issue. If you keep having problems just submit another issue :)

good luck!
