### ISSUE TITLE
3D-Assembly

### ISSUE THREAD

**Issue by orso7** [veebch/photon#21]
Is there a chance that you will offer a 3D-Assembly? 
At least for the printable parts? or share the parts in a neutral solid format like STEP? I would love to build the Pico Lipo version but might try to modify the case a bit.

**Comment by veebch** [comment]
You could alter it by importing it into freecad (or your chosen tool) and converting it to a mesh. I'll also look at adding the original source files to the repository.

**Comment by orso7** [comment]
What program did you use to design the source files?

If not available otherwise I will probably rebuild the Pico LiPo version in Solidworks since mesh isn't fun to edit there, solids are better.
