### ISSUE TITLE
Finer Aperture values and lux values

### ISSUE THREAD

**Issue by orso7** [veebch/photon#23]
Is it possible to get the Software to show finer aperture Values (like 1/6th or the exact decimal value)? 
Also is it possible to display lux values?

I am going to build the original one but plan on modifying it for a special purpose.

**Comment by veebch** [comment]
That should be easy, you'd just need to increase the number of values for aperture in the code. Readings currently get rounded to the nearest value. Increasing the values in the code will make it 'finer'
