### ISSUE TITLE
flash?

### ISSUE THREAD

**Issue by ryan1894** [veebch/photon#24]
it would be awesome to have this be almost 1:1 with e.g. a sekonic l-308

**Comment by veebch** [comment]
Totally agree. If no one adds that capability, I will brush up on my low level electronics and try to figure out how to make a start on it.

**Comment by veebch** [comment]
[ Done!](https://www.veeb.ch/projects/flash-aaahhh-ahhhhhh)

**Comment by ryan1894** [comment]
😱
