### ISSUE TITLE
How to attach rotary encoder?

### ISSUE THREAD

**Issue by ryan1894** [veebch/photon#26]
My rotary encoder came without a breakout board, and according to most pictures, the middle of the 3 pins and one of the two pins are connected to ground

but I can't get my rotary encoder to output anything when connected to arduino lab for micropython

Am I supposed to connect to middle of 3 pin to VCC?

Edit: I have it working in arduino lab, but outA.value is always equal to outB.value for both directions

theyre either both 0 or both 1

For reference I am using an EC-11 rotary encoder I pulled from a previous keyboard project. It seems that the pico is checking too slow?

**Comment by veebch** [comment]
I've only used them on a breakout board. The micropython.org forum might be useful

**Comment by ryan1894** [comment]
wow ok looks like my gpio pint 6 and 7 were actually shorted due to bad soldering.

i had to make pin 6 and 7 both PULLUP resistors but otherwise it totally works
