### ISSUE TITLE
Cannot get ampy to install to Windows Powershell

### ISSUE THREAD

**Issue by BadRothenfelde** [veebch/photon#29]
I am trying to get the software-side of this project to work - to no avail. 
I have installed Python on my Windows Laptop. 
I then need to install the python package installer (pip) and only then can I install ampy and thusly the photon software. 

Am I understanding this correctly from a newbs' perspective? 

Thanks for the help in advance and greetings from Cologne.

**Comment by veebch** [comment]
Hello Cologne! 
I've not installed it on windows but what you describe sounds sensible. Have you tried WSL? https://learn.microsoft.com/en-us/windows/wsl/install. It has worked well for me in the past.

Tip:
If you're ever in a situation where there is an issue transferring files to a pico and there aren't that many files you need to make, then you always have the option of making them with Thonny. It's a bit of a hack, but it works in a pinch :)

Good luck with the build
