### ISSUE TITLE
required files result in error

### ISSUE THREAD

**Issue by jonyv0992** [veebch/photon#3]
After the update to the read me file the last step of installing the files to the pico result in an Error: Invalid value for each of the commands. Could the files be uploaded to the pico using Thonny?

**Comment by veebch** [comment]
There are a few things you could use: rshell, ampy or thonny. In my experience, ampy was the most reliable and involved least effort. 
It sounds like your ampy installation might be playing up. Try looking at the linked guide on the readme and see if the commands listed in the readme make sense.

**Comment by veebch** [comment]
(specifically, check the port name... I've updated the readme to try to be clearer)
