### ISSUE TITLE
im missing something

### ISSUE THREAD

**Issue by Stefanvoor** [veebch/photon#7]
Hi, im pretty new to this sort of thing and running into an issue.
when i run de code in thonny i get an error, name 'ssd' isn't defined.
am i doing something wrong here or is there something im not seeing, being a novice at this?

i am using a pico lipo board with  pimoroni-picolipo_16mb-v1.19.10-micropython.uf2 

>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 195, in <module>
  File "<stdin>", line 24, in splash
NameError: name 'ssd' isn't defined
>>>

**Comment by veebch** [comment]
Welcome aboard :)

It looks like the file that defines ssd might not be loaded onto the pi? Is the OLED screen connected?

**Comment by Stefanvoor** [comment]
Yes the Oled is connected, when i run gui\demos\aclock.py it seems to be working. i get a clock on the display when its running

**Comment by veebch** [comment]
that gets ssid from a different place...... can you check that drivers/ssd1351/ssd1351_16bit.py is on the pico?

**Comment by Stefanvoor** [comment]
they are indeed on the pico

**Comment by veebch** [comment]
Looking at the code it looks like there is an issue with the sensor that means that you've found a bug.

**Comment by Stefanvoor** [comment]
yes, its working perfectly over usb now, but when i power it on via a lipo its not running. the power light is on but the screen isnt coming up.

**Comment by veebch** [comment]
Progress!

I've not encountered the problem with the lipo. I seem to recall that if you power it on via the lipo then you can still connect to thonny over usb. So you could run it interactively to get a better idea of the issue.

**Comment by veebch** [comment]
Closing so you can add the specific LiPo issue, in the hope that someone can help
