### ISSUE TITLE
Resin vs PLA

### ISSUE THREAD

**Issue by yhax** [veebch/photon#9]
Hi there, finished the build, it's awesome, thank you for making it and sharing it! One q I have is related to the lumisphere. Can you share the print settings you used for the lumisphere? I'd like to compare it to the FDM versions I printed. Thank you. (also one small note, for the back pico lipo case, I found M3 screws to be a better fit for the bigger holes - not sure if that was a typo or my printer is just crazy :) )

**Comment by veebch** [comment]
The expert is @040medien :)

**Comment by 040medien** [comment]
Oh, you're right - they are M3 threads - I'll fix the documentation.

For the Lumisphere I printed it in white "ABS like" resin with 9 seconds of exposure per layer. Layer height was 0.05mm.
